### PR TITLE
Streamline dist client state management and prune remaining `reqwest::blocking` client

### LINKED ISSUE #85: tokio context issue on failed compilation unit
Attempting to compile github.com/drahnr/honggfuzz-rs @ 99fec3373f8399b4664cda47f6b120a951e405be in _dist_ mode with the following client config:

```toml
[dist]
scheduler_url = "https://internal.yada.youknow"
toolchains = []
toolchain_cache_size = 5368709120

[dist.auth]
type = "token"
token = "s3cr3tt0ken"
```

leads to

```
RUST_BACKTRACE=1 RUST_LOG=sccache=debug SCCACHE_START_SERVER=1 SCCACHE_NO_DAEMON=1 sccache
thread 'tokio-runtime-worker' panicked at 'Cannot start a runtime from within a runtime. This happens because a function (like `block_on`) attempted to block the current thread while the thread is being used to drive asynchronous tasks.', /home/bernhard/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.25/src/runtime/enter.rs:38:5
stack backtrace:
   0: std::panicking::begin_panic
   1: tokio::runtime::enter::enter
   2: tokio::runtime::context::enter
   3: sccache::server::DistClientContainer::create_state
   4: sccache::server::DistClientContainer::get_client
   5: sccache::server::SccacheService<C>::handle_compile::{{closure}}
   6: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
   7: <futures_util::stream::try_stream::try_flatten::TryFlatten<St> as futures_core::stream::Stream>::poll_next
   8: <futures_util::stream::stream::forward::Forward<St,Si,Item> as core::future::future::Future>::poll
   9: <futures_util::future::future::map::Map<Fut,F> as core::future::future::Future>::poll
  10: tokio::runtime::task::core::Core<T,S>::poll
  11: <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
  12: tokio::runtime::task::harness::Harness<T,S>::poll
  13: std::thread::local::LocalKey<T>::with
  14: tokio::runtime::thread_pool::worker::Context::run_task
  15: tokio::runtime::thread_pool::worker::Context::run
  16: tokio::macros::scoped_tls::ScopedKey<T>::set
  17: tokio::runtime::thread_pool::worker::run
  18: tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut
  19: <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
  20: tokio::runtime::task::harness::Harness<T,S>::poll
  21: tokio::runtime::blocking::pool::Inner::run
  22: tokio::runtime::context::enter
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: "PoisonError { inner: .. }"', src/server.rs:272:36
stack backtrace:
   0: rust_begin_unwind
             at /rustc/88f19c6dab716c6281af7602e30f413e809c5974/library/std/src/panicking.rs:493:5
   1: core::panicking::panic_fmt
             at /rustc/88f19c6dab716c6281af7602e30f413e809c5974/library/core/src/panicking.rs:92:14
   2: core::option::expect_none_failed
             at /rustc/88f19c6dab716c6281af7602e30f413e809c5974/library/core/src/option.rs:1329:5
   3: sccache::server::DistClientContainer::get_client
   4: sccache::server::SccacheService<C>::handle_compile::{{closure}}
   5: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
   6: <futures_util::stream::try_stream::try_flatten::TryFlatten<St> as futures_core::stream::Stream>::poll_next
   7: <futures_util::stream::stream::forward::Forward<St,Si,Item> as core::future::future::Future>::poll
   8: <futures_util::future::future::map::Map<Fut,F> as core::future::future::Future>::poll
   9: tokio::runtime::task::core::Core<T,S>::poll
  10: <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
  11: tokio::runtime::task::harness::Harness<T,S>::poll
  12: std::thread::local::LocalKey<T>::with
  13: tokio::runtime::thread_pool::worker::Context::run_task
  14: tokio::runtime::thread_pool::worker::Context::run
  15: tokio::macros::scoped_tls::ScopedKey<T>::set
  16: tokio::runtime::thread_pool::worker::run
  17: tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut
  18: <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
  19: tokio::runtime::task::harness::Harness<T,S>::poll
  20: tokio::runtime::blocking::pool::Inner::run
  21: tokio::runtime::context::enter
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

### PR DESCRIPTION
**Pull request by Xanewok**
This is an attempt to fix #85 (and is an overdue cleanup).

First 3 commits do the aforementioned streamlining, while the remaining commits prune the remaining blocking `reqwest` client. Since we can now leverage streaming bodies in async client, there's no need to fallback to the blocking implementation. This should have a side-benefit of not constructing any blocking/runtime machinery while we're in an async context - this, ultimately, should prevent us from hitting the panics mentioned in #85.

I couldn't reasonably reproduce the issue from #85, so @drahnr let me know if that fixes things for you (and let's see what CI has to say first since I didn't run too much tests locally yet).

### CODE REVIEW

File: src/server.rs [hunk 1]
```diff
@@ -255,57 +256,59 @@ impl DistClientContainer {
...
+        let state = &mut *guard;
         Self::maybe_recreate_state(state);
-        let res = match state {
-            DistClientState::Some(_, dc) => Ok(Some(dc.clone())),
+
+        match *state {
+            DistClientState::FailWithMessage(_, _) => {
+                let (config, msg) = match mem::replace(state, DistClientState::Disabled) {
+                    DistClientState::FailWithMessage(config, msg) => (config, msg),
+                    _ => unreachable!(),
```
Comment (drahnr) [inline src/server.rs:292]: nit: Add a message in the `unreachable!`

File: src/server.rs [hunk 2]
```diff
@@ -225,8 +225,7 @@ impl DistClientContainer {
             | DistClientState::FailWithMessage(cfg, _)
             | DistClientState::RetryCreateAt(cfg, _) => {
                 warn!("State reset. Will recreate");
-                *state =
-                    DistClientState::RetryCreateAt(cfg, Instant::now() - Duration::from_secs(1));
+                *state = DistClientState::RetryCreateAt(cfg, Instant::now());
```
Comment (drahnr) [inline src/server.rs:228]: :+1:

**Review by drahnr — APPROVED** [review]

File: src/dist/http.rs [hunk 3]
```diff
@@ -1236,9 +1237,9 @@ mod client {
         async fn do_get_status(&self) -> Result<SchedulerStatusResult> {
             let scheduler_url = self.scheduler_url.clone();
             let url = urls::scheduler_status(&scheduler_url);
-            let req = self.client.lock().unwrap().get(url);
+            let req = self.client_async.lock().unwrap().get(url);
 
-            self.pool.spawn_blocking(move || bincode_req(req)).await?
+            bincode_req_fut(req).await
```
Comment (drahnr) [inline src/dist/http.rs:1204]: :heart:

File: src/dist/http.rs [hunk 4]
```diff
@@ -1249,16 +1250,19 @@ mod client {
...
-                        })
-                        .await?
+                    let req = self.client_async.lock().unwrap().post(url);
+
+                    let _toolchain_file_exists = toolchain_file.metadata()?;
+
+                    use tokio_util::codec::{BytesCodec, FramedRead};
+                    let toolchain_file = toolchain_file.into_parts().0;
+                    let toolchain_file = tokio::fs::File::from_std(toolchain_file);
+                    let stream = FramedRead::new(toolchain_file, BytesCodec::new());
```
Comment (drahnr) [inline src/dist/http.rs:1222]: Soo much better! Ty

**Comment by Xanewok** [comment]
We do not `block_on` anymore in `get_client` due to new async interface in ecba086663c43abcfcc323389bc45b8fd297e844 (which caused panics when executed in the task context) and added a note wrt deadlock-safety in 8ebef65d3f001696cada74b40bf043f98b376f0b.
